name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Actualiza a la versión de Node.js indicada en el mensaje de error
    
      - name: Install Dependencies
        run: npm install # o yarn install si estás usando yarn
    
      - name: Build
        run: npm run build # o el comando de construcción que corresponda a tu proyecto
    
      - name: Deploy
        run: |
          git config --global user.email "valentina.cedano57@gmail.com"
          git config --global user.name "Valentina Cedano"
          git checkout gh-pages
          cp -r ./* ..  # Copia todos los archivos a la carpeta raíz
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
    